language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

# commands to run tests and style check
script:
  - flake8 . || echo "Flake8 failed"
  - nosetests --with-coverage --cover-erase --cover-branches --cover-package=fleet

after_success:
  - coveralls
